version: "3"
services:
  db:
    image: postgres:11.1-alpine
  django:
    build: .
    volumes:
      - .:/usr/src/menu
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
